modLoader="lowcodefml"
loaderVersion="[37,)"
issueTrackerURL="${github}/issues"
license="Apache License, Version 2.0"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${display_name}"
authors="AnAwesomGuy"
description="${description}"
logoFile="assets/${mod_id}/icon.png"

[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="[37,)"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="[1.17,)"