plugins {
    id "architectury-plugin" version "3.5-SNAPSHOT"
    id "dev.architectury.loom-no-remap" version "1.17-SNAPSHOT" apply false
    id "com.gradleup.shadow" version "9.5.+"
    id "me.modmuss50.mod-publish-plugin" version "2.+" apply false
}

apply plugin: "me.modmuss50.mod-publish-plugin"

architectury.minecraft = minecraft_version

Map<String, String> modProperties() {
    [
            version    : mod_version, mod_id: mod_id,   description  : project.properties.description,
            github_repo: 'http://github.com/' + github, display_name : display_name,
            modrinth_id: modrinth_id,                   curseforge_id: curseforge_id,
    ]
}


import groovy.json.JsonOutput
import groovy.json.JsonSlurper

subprojects {
    apply plugin: "dev.architectury.loom-no-remap"
    apply plugin: "architectury-plugin"

    dependencies {
        minecraft "com.mojang:minecraft:$minecraft_version"
    }

    processResources {
        def properties = modProperties()
        inputs.properties properties

        filesMatching(["META-INF/*mods.toml", "fabric.mod.json", "pack.mcmeta"]) {
            expand properties
            filter { it.empty ? null : it }
        }

        doLast {
            fileTree(dir: outputs.files.asPath, includes: ["**/*.json", "**/*.mcmeta"]).each {
                it.text = JsonOutput.toJson(new JsonSlurper().parse(it))
            }
        }
    }

    loom {
        runs {
            configureEach {
                systemProperties.putAll(['mixin.debug': 'true', 'fabric.log.level': 'debug'])
            }
        }
    }

    jar {
        archiveAppendix = project.name
        archiveClassifier = 'dev'
    }
}

allprojects {
    apply plugin: "java"
    apply plugin: "maven-publish"

    base.archivesName = mod_id

    version = mod_version + "+" + minecraft_version
    group = maven_group

    repositories {
        exclusiveContent {
            forRepositories maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
            filter {
                includeGroup "maven.modrinth"
            }
        }


        exclusiveContent {
            forRepositories maven {
                name = 'ParchmentMC'
                url = 'https://maven.parchmentmc.org'
            }
            filter {
                includeGroup "org.parchmentmc.data"
            }
        }
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = "UTF-8"
        options.release = 25
//        options.compilerArgs << '-g:none'
    }

    java {
//        withSourcesJar()
        toolchain.languageVersion = JavaLanguageVersion.of(25)
    }

    [jar/*, sourcesJar*/]*.configure {
        from 'LICENSE'
    }

    // repoducible builds
    tasks.withType(AbstractArchiveTask).configureEach {
        preserveFileTimestamps = false
        reproducibleFileOrder = true

        filePermissions { unix('644') }
        dirPermissions { unix('755') }
    }
}

dependencies {
    shadow(project(':common')) { transitive = false }
}

jar {
    archiveClassifier = 'EMPTY'
}

shadowJar {
    configurations = [project.configurations.shadow]

    archiveAppendix = 'universal'
    archiveClassifier = ''

    from project.project(":fabric").sourceSets.main.output.resourcesDir
    from project.project(":neoforge").sourceSets.main.output.resourcesDir

    manifest.attributes.put 'MixinConfigs', mod_id + '.mixins.json'
}.dependsOn(project.project(":fabric").processResources, project.project(":neoforge").processResources)

publishMods {
    changelog = project.changelog
    type = STABLE

//    def fabricJar = project.provider { project(":fabric").shadowJar }.flatMap { it.archiveFile }
//    def neoForgeJar = project.provider { project(":neoforge").shadowJar }.flatMap { it.archiveFile }
    def universalJar = project.provider { rootProject.shadowJar }.flatMap { it.archiveFile }

    file = universalJar
//    additionalFiles.from fabricJar, neoforgeJar
    version = project.version
    displayName = "[All Loaders 26.x] $display_name $project.version"
    modLoaders.addAll "fabric", "neoforge", "forge"

    curseforge {
        accessToken = providers.environmentVariable('CURSEFORGE_TOKEN')
        dryRun = !accessToken.present
        projectId = curseforge_id
        clientRequired = true
        serverRequired = true

        minecraftVersionRange {
            start = "26.1"
            end = "latest"
        }
    }

    modrinth {
        accessToken = providers.environmentVariable('MODRINTH_TOKEN')
        dryRun = !accessToken.present
        projectId = modrinth_id
        environment = CLIENT_AND_SERVER

        minecraftVersionRange {
            start = "26.1-snapshot-1"
            end = "latest"
            includeSnapshots = true
        }
    }

    github {
        accessToken = providers.environmentVariable('GITHUB_TOKEN')
        dryRun = !accessToken.present
        repository = github
        commitish = "26.x"
        tagName = project.version
    }
}