plugins {
    id "dev.architectury.loom" version "1.9-SNAPSHOT" apply false
    id "architectury-plugin" version "3.4-SNAPSHOT"
    id "com.github.johnrengelman.shadow" version "8.1.+" apply false
    id "me.modmuss50.mod-publish-plugin" version "0.8.+" apply false
}

apply plugin: "me.modmuss50.mod-publish-plugin"

architectury.minecraft = minecraft_version

Map<String, String> modProperties() {
    [
            version: mod_version, mod_id: mod_id, description: project.properties.description,
            github_repo: 'http://github.com/' + github, display_name: display_name,
            modrinth_id: modrinth_id, curseforge_id: curseforge_id,
    ]
}

import groovy.json.JsonOutput
import groovy.json.JsonSlurper
import net.fabricmc.loom.task.AbstractRemapJarTask

subprojects {
    apply plugin: "dev.architectury.loom"
    apply plugin: "architectury-plugin"

    dependencies {
        minecraft "com.mojang:minecraft:$minecraft_version"
        mappings loom.layered() {
            officialMojangMappings()
            parchment "org.parchmentmc.data:parchment-1.21.1:2024.11.17@zip"
        }
    }

    processResources {
        def properties = modProperties()
        inputs.properties properties

        filesMatching(["META-INF/*mods.toml", "fabric.mod.json", "pack.mcmeta"]) {
            expand properties
            filter { it.empty ? null : it }
        }

        doLast {
            fileTree(dir: outputs.files.asPath, includes: ["**/*.json", "**/*.mcmeta"]).each {
                it.text = JsonOutput.toJson(new JsonSlurper().parse(it))
            }
        }
    }

    tasks.withType(AbstractRemapJarTask).configureEach {
        archiveAppendix = project.name
    }
}

allprojects {
    apply plugin: "java"
    apply plugin: "maven-publish"

    base.archivesName = mod_id

    version = mod_version + "+" + minecraft_version
    group = maven_group

    repositories {
        exclusiveContent {
            forRepositories maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
            filter {
                includeGroup "maven.modrinth"
            }
        }


        exclusiveContent {
            forRepositories maven {
                name = 'ParchmentMC'
                url = 'https://maven.parchmentmc.org'
            }
            filter {
                includeGroup "org.parchmentmc.data"
            }
        }
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = "UTF-8"
        options.release = 21
//        options.compilerArgs << '-g:none'
    }

    java.withSourcesJar()

    [jar, sourcesJar]*.configure {
        from 'LICENSE'
    }
}

publishMods {
    changelog = project.changelog
    type = STABLE
    def fabricJar = project.provider { project(":fabric").remapJar }.flatMap { it.archiveFile }
    def fabricSources = project.provider { project(":fabric").remapSourcesJar }.flatMap { it.archiveFile }
    def neoForgeJar = project.provider { project(":neoforge").remapJar }.flatMap { it.archiveFile }
    def neoForgeSources = project.provider { project(":neoforge").remapSourcesJar }.flatMap { it.archiveFile }

    def fabric = publishOptions {
        file = fabricJar
        additionalFiles.from fabricSources
        version = project.version + "-fabric"
        displayName = "[Fabric 1.20.5-1.21.1] $display_name $project.version"
        modLoaders.addAll "fabric", "quilt"
    }

    def neoForge = publishOptions {
        file = neoForgeJar
        additionalFiles.from neoForgeSources
        version = project.version + "-neoforge"
        displayName = "[(Neo)Forge 1.20.5-1.21.1] $display_name $project.version"
        modLoaders.add "neoforge"
    }

    def modrinthOptions = modrinthOptions {
        accessToken = providers.environmentVariable('MODRINTH_TOKEN')
        dryRun = !accessToken.present
        projectId = modrinth_id
    }

    def curseOptions = curseforgeOptions {
        accessToken = providers.environmentVariable('CURSEFORGE_TOKEN')
        dryRun = !accessToken.present
        projectId = curseforge_id
        clientRequired = true
        serverRequired = true
    }

    curseforge("curseFabric") {
        from curseOptions, fabric
        minecraftVersionRange {
            start = "1.20.5"
            end = "1.21.1"
        }
    }

    curseforge("curseNeoForge") {
        from curseOptions, neoForge
        minecraftVersionRange {
            start = "1.20.5"
            end = "1.21.1"
        }
    }

    modrinth("modrinthFabric") {
        from modrinthOptions, fabric
        minecraftVersionRange {
            start = "24w12a"
            end = "24w34a"
            includeSnapshots = true
        }
    }

    modrinth("modrinthNeoForge") {
        from modrinthOptions, neoForge
        minecraftVersionRange {
            start = "1.20.5"
            end = "1.21.1"
        }
    }

    github {
        additionalFiles.from fabricJar, neoForgeJar, fabricSources, neoForgeSources
        accessToken = providers.environmentVariable('GITHUB_TOKEN')
        dryRun = !accessToken.present
        repository = github
        commitish = "20.5-21.1"
        tagName = project.version
    }
}