org.gradle.jvmargs=-Xmx2048M

minecraft_version=1.21.4
enabled_platforms=fabric,neoforge

mod_id=breakingbedrock
mod_version=1.1.4
maven_group=net.anawesomguy.breakingbedrock
description=Allow bedrock to be mined with a netherite pickaxe!
github=AnAwesomGuy/breakingbedrock
display_name=Breaking Bedrock

fabric_loader_version=0.16.10
fabric_api_version=0.114.3+1.21.4

neoforge_version=21.4.59-beta

changelog=update to 1.21.2+
curseforge_id=1017910
modrinth_id=s0tNTkDN

#testing mods
modernfix_version=5.20.1+mc1.21.4
ferrite_core_version=7.1.1
#sodium_version=mc1.21.1-0.6.5