org.gradle.jvmargs=-Xmx2048M

minecraft_version=26.2
enabled_platforms=fabric,neoforge

mod_id=breakingbedrock
mod_version=1.3.0
maven_group=net.anawesomguy.breakingbedrock
description=Allow bedrock to be mined with a netherite pickaxe!
github=AnAwesomGuy/breakingbedrock
display_name=Breaking Bedrock

fabric_loader_version=0.19.3
fabric_api_version=0.154.1+26.2

neoforge_version=26.2.0.8-beta
forge_version=65.0.3

changelog=update to 26.+\n\
  you didn't need to vibe code a port lmao
curseforge_id=1017910
modrinth_id=s0tNTkDN

#testing mods
#ferrite_core_version=8.0.0